### PR TITLE
Fix spelling and formatting issues in README

### PR DESCRIPTION
**Pull request by JamesSkemp**
Noticed a typo and what looked to be a couple markdown formatting issues.

Before the movement controls there's also this bitin

> but soon will eventually integrate examples

I would recommend just picking one (soon or eventually) and using it.

- ... but soon will integrate examples ...
- ... but will eventually integrate examples ...

### CODE REVIEW

**Comment by the-simian** [comment]
Thanks, James, I've been sick for many days I'm just now catching up on some of this stuff

**Comment by the-simian** [comment]
this is no longer necessary I changed the readme.

**Comment by JamesSkemp** [comment]
Sounds good.

Note you still have a weirdly worded sentence:

"but soon will eventually integrate examples"

**Comment by the-simian** [comment]
thanks @JamesSkemp the whole readme is going to change when I make it a scaffold. I got pulled away for a long time on this, but I'm working regularly now so I think that might be sooner rather than later, thankfully

**Pull request closed without merging**
